/*
 * Copyright (c) 2015 by Gerrit Grunwald
 * Updated by Patrick Kutch for Java 21 & Gradle 8/9 compatibility
 */

// FlipPanel
plugins {
    id 'java-library'
    id 'application'
    id 'org.openjfx.javafxplugin'
}

repositories {
    mavenCentral()
}

javafx {
    version = "21.0.3"
    modules = [ 'javafx.controls' ]
}

application {
    mainClass = 'eu.hansolo.enzo.ledbargraph.Demo'
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/main/resources', 'src/main/java']
        }
    }
}

dependencies {
    implementation project(':Led')
}
